# Template: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build On Linux

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      run: |

        pip install conan==2.6.0

        conan profile detect

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |

        conan install . --build=missing

        cmake --preset cmake-project-release -DWITH_GTEST=ON

    - name: Build Targets
      working-directory: ${{github.workspace}}
      run: cmake --build --preset cmake-project-release

    - name: Run Unit Test
      working-directory: ${{github.workspace}}
      run: cmake --build --preset cmake-project-release -t tests
