# Template: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build On Linux

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |

        mkdir -p build && cd build

        cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make
