# Template: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build On Windows

on:
  push:
    branches:
    - feature-liuzx-unit-test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      run: pip install conan==2.6.0

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |

        conan install .

        cmake --preset cmake-project-default -DWITH_GTEST=ON

    - name: Build Targets
      working-directory: ${{github.workspace}}
      run: cmake --build --preset cmake-project-release

    - name: Run Unit Test
      working-directory: ${{github.workspace}}
      run: cmake --build --preset cmake-project-release -t tests
