# Template: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Run Unit Test On Linux

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GoogleTest
      working-directory: ${{github.workspace}}
      run: |

        cd ..

        wget https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz

        tar -zxvf release-1.12.1.tar.gz && cd googletest-release-1.12.1

        mkdir -p build && cd build

        cmake ..

        make

        sudo make install

    - name: Configure CMake With Unit Test
      working-directory: ${{github.workspace}}
      run: |

        mkdir -p build && cd build

        cmake -DWITH_GTEST=ON ..

    - name: Run Unit Test
      working-directory: ${{github.workspace}}/build
      run: make tests
